version: "3.8"
services:
  rust:
    build:
      context: . # Dockerfileで親ディレクトリを参照するときに使うらしいぞ
      dockerfile: ./docker/rust/Dockerfile
    tty: true
    container_name: rust
    volumes:
      - .:/usr/src/rust
